# Site
name: 'The Incident'
description: 'Welcome to The Incident, an independent journalism news website dedicated to shedding light on the critical issues impacting politics, economics, AI, and corruption.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-96.png'
baseurl: ''
url: "https://theincident.github.io" # the base hostname & protocol for your site, e.g. https://example.com
disqus: 'theincident'
email: 'isaacjosephhorton@gmail.com'
mailchimp-list: 'https://9788cad7.sibforms.com/serve/MUIEAFe1VP-NTFTRooakVFt_S9f4Ek2XsQbrhGKoq-rYQqOV14nreWWr3PPBb6l60_Ef5jQxOq_brugKCn0LJe02eti3x_RAZDiNmMMx7luDftIe0PzSLL6XcAqUUfDXhN4xotTOM8h3SzILNLXgVAZIN3JLxg3KH2nP07QX68LFkQK3ZsmYGC5q0C9VHk9xGRUPNKY6fCJW-LI-'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    isaac:
      name:           Isaac Horton
      site:           https://kre8t.github.io/
      avatar:         /assets/images/isaac.jpg
      bio:            "Isaac Horton is the passionate writer and creator of The Incident. He has a strong dedication to free speech, exposing corruption, and investigative journalism. With a deep desire to uncover the truth behind the workings of the powerful, Isaac is committed to exposing corrupt schemes and disarming propaganda machinery. His focus on politics, economics, AI, and corruption is fueled by a desire to shine a light on critical issues that impact our world today. Isaac's commitment to uncovering the truth is evident in his reporting, which delves deep into complex issues to provide readers with a comprehensive understanding of events shaping our world. Isaac's unwavering dedication to ethical standards ensures that The Incident's reporting is entirely independent and unbiased, making it a reliable source of information for readers."
      email:          isaacjosephhorton@gmail.com
      twitter:        https://twitter.com/kre8t_

    harley:
      name:           harley
      site:           https://kre8t.github.io/
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          harleysavij@gmail.com
      twitter:        https://twitter.com/harleysavij

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: isaac
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
